"""
pages/3_dashboard.py  —  Phase 8: Admin Dashboard & Manual Review Queue

Shows:
  - KPI metric row (plans generated, avg coverage, avg traceability, total flags)
  - Plans generated per role (bar chart)
  - Status distribution (pie chart)
  - Manual review queue (comparison results != Pass) with Approve/Reject/Regenerate
  - Audit trail: reviewer decisions are stored as linked records; original
    Pipeline 1/2 output is NEVER overwritten.
"""

import json
import streamlit as st
import plotly.express as px
import pandas as pd

from core.db import (
    get_dashboard_metrics,
    get_requirements_per_role_df,
    get_comparison_results_df,
    get_review_queue_df,
    log_review_decision,
    setup_db,
)
from core.comparison import compare

st.set_page_config(
    page_title="Admin Dashboard - SkillSprint AI",
    page_icon="📊",
    layout="wide",
)

# ── Auth guard ────────────────────────────────────────────────────────────────
if st.session_state.get("user_role") != "Admin":
    st.warning("You must be logged in as an Admin to view this page.")
    st.stop()

# Ensure all tables (including new ones) exist before querying
setup_db()

st.title("📊 Admin Dashboard")

# ── 1. Top-level KPI metrics ──────────────────────────────────────────────────
st.subheader("System Overview")

try:
    doc_count, chunk_count, req_count = get_dashboard_metrics()
    comp_df = get_comparison_results_df()

    total_plans      = len(comp_df)
    avg_coverage     = comp_df["coverage_score"].mean()     if not comp_df.empty else 0.0
    avg_traceability = comp_df["traceability_score"].mean() if not comp_df.empty else 0.0

    # Count all flags across all runs
    total_flags = 0
    if not comp_df.empty and "flags_json" in comp_df.columns:
        for fj in comp_df["flags_json"].dropna():
            try:
                total_flags += len(json.loads(fj))
            except (json.JSONDecodeError, TypeError):
                pass

    c1, c2, c3, c4, c5, c6 = st.columns(6)
    c1.metric("📄 Documents Ingested",     doc_count)
    c2.metric("🧩 Chunks Indexed",         chunk_count)
    c3.metric("📋 Matrix Requirements",    req_count)
    c4.metric("🤖 Plans Generated",        total_plans)
    c5.metric("📈 Avg Coverage",           f"{avg_coverage:.1f}%")
    c6.metric("⚠️ Total Flags Raised",     total_flags)

except Exception as exc:
    st.error(f"Error loading KPIs: {exc}")

st.divider()

# ── 2. Charts ─────────────────────────────────────────────────────────────────
col_left, col_right = st.columns(2)

with col_left:
    st.subheader("Plans Generated per Role")
    try:
        if not comp_df.empty:
            role_counts = comp_df.groupby("role").size().reset_index(name="count")
            fig_bar = px.bar(
                role_counts,
                x="role", y="count",
                title="Plans Generated by Role",
                labels={"count": "Plans", "role": "Role"},
                color="count",
                color_continuous_scale="Blues",
            )
            fig_bar.update_layout(showlegend=False, coloraxis_showscale=False,
                                  xaxis_tickangle=-30)
            st.plotly_chart(fig_bar, use_container_width=True)
        else:
            st.info("No plans generated yet.")
    except Exception as exc:
        st.error(f"Chart error: {exc}")

with col_right:
    st.subheader("Verification Status Distribution")
    try:
        if not comp_df.empty:
            status_counts = comp_df.groupby("overall_status").size().reset_index(name="count")
            STATUS_COLORS = {
                "Pass":               "#22c55e",
                "Warning":            "#f59e0b",
                "Fail":               "#ef4444",
                "Generation Failed":  "#7c3aed",
            }
            fig_pie = px.pie(
                status_counts,
                names="overall_status",
                values="count",
                title="Plan Status Distribution",
                color="overall_status",
                color_discrete_map=STATUS_COLORS,
                hole=0.4,
            )
            st.plotly_chart(fig_pie, use_container_width=True)
        else:
            st.info("No status data yet.")
    except Exception as exc:
        st.error(f"Chart error: {exc}")

st.divider()

# ── 3. Average traceability score per role ────────────────────────────────────
st.subheader("Average Traceability Score per Role")
try:
    if not comp_df.empty:
        trace_df = comp_df.groupby("role")["traceability_score"].mean().reset_index()
        trace_df.columns = ["role", "avg_traceability"]
        fig_trace = px.bar(
            trace_df, x="role", y="avg_traceability",
            title="Avg Traceability Score by Role (%)",
            labels={"avg_traceability": "Avg Traceability (%)", "role": "Role"},
            color="avg_traceability",
            color_continuous_scale="Greens",
            range_y=[0, 100],
        )
        fig_trace.update_layout(coloraxis_showscale=False, xaxis_tickangle=-30)
        st.plotly_chart(fig_trace, use_container_width=True)
    else:
        st.info("No data yet.")
except Exception as exc:
    st.error(f"Chart error: {exc}")

st.divider()

# ── 4. Manual Review Queue ────────────────────────────────────────────────────
st.subheader("🔍 Manual Review Queue")
st.caption(
    "All plans with status **Warning**, **Fail**, or **Generation Failed**. "
    "Approve/Reject actions are stored as audit records — original outputs are never overwritten."
)

try:
    queue_df = get_review_queue_df()
except Exception as exc:
    st.error(f"Could not load review queue: {exc}")
    queue_df = pd.DataFrame()

if queue_df.empty:
    st.success("✅ Review queue is empty — no flagged plans.")
else:
    STATUS_ICON = {
        "Warning":            "🟡",
        "Fail":               "🔴",
        "Generation Failed":  "🔴",
    }
    DECISION_ICON = {
        "Approved":  "✅",
        "Rejected":  "❌",
        None:        "⏳ Pending",
    }

    for _, row in queue_df.iterrows():
        cid        = row["comparison_id"]
        emp_id     = row["employee_id"]
        role       = row["role"]
        status     = row["overall_status"]
        cov        = row.get("coverage_score", 0) or 0
        trace      = row.get("traceability_score", 0) or 0
        ts         = row.get("timestamp", "")
        decision   = row.get("reviewer_decision")
        notes_prev = row.get("reviewer_notes", "")

        # Parse flags
        flags = []
        try:
            flags = json.loads(row.get("flags_json") or "[]")
        except (json.JSONDecodeError, TypeError):
            pass

        icon = STATUS_ICON.get(status, "⚪")
        dec_label = DECISION_ICON.get(decision, f"✅ {decision}")

        header = (
            f"{icon} **{emp_id}** — {role} | "
            f"Status: `{status}` | "
            f"Decision: {dec_label} | "
            f"Coverage: {cov:.0f}% | "
            f"Flags: {len(flags)} | "
            f"_{ts}_"
        )

        with st.expander(header, expanded=(decision is None)):

            # Flags breakdown
            if flags:
                st.write("**Validation Flags:**")
                for f in flags:
                    ftype  = f.get("type", "")
                    detail = f.get("detail", "")
                    mname  = f.get("module_name") or f.get("requirement_id", "")
                    if ftype in ("Fail", "Missing-mandatory", "Unsupported-claim"):
                        st.error(f"`{ftype}` — {mname}: {detail}")
                    elif ftype in ("Warning", "Outdated-policy", "Duplicate"):
                        st.warning(f"`{ftype}` — {mname}: {detail}")
                    else:
                        st.info(f"`{ftype}` — {mname}: {detail}")
            else:
                st.write("_No flag details stored._")

            st.write(f"**Avg Coverage:** {cov:.1f}%  |  "
                     f"**Avg Traceability:** {trace:.1f}%")

            if decision:
                st.info(f"**Current Decision:** {decision}"
                        + (f" — _{notes_prev}_" if notes_prev else ""))

            # Reviewer notes input
            notes_key = f"notes_{cid}"
            notes = st.text_area(
                "Reviewer notes (optional)",
                key=notes_key,
                placeholder="Add context for the audit trail…",
                height=68,
            )

            # Action buttons
            b1, b2, b3 = st.columns(3)

            # ── Approve ──────────────────────────────────────────────────────
            if b1.button("✅ Approve", key=f"approve_{cid}"):
                log_review_decision(
                    comparison_id=cid,
                    employee_id=emp_id,
                    role=role,
                    original_status=status,
                    reviewer_decision="Approved",
                    reviewer_notes=notes or "",
                )
                st.success(f"Approved: {emp_id} / {role}")
                st.rerun()

            # ── Reject ───────────────────────────────────────────────────────
            if b2.button("❌ Reject", key=f"reject_{cid}"):
                log_review_decision(
                    comparison_id=cid,
                    employee_id=emp_id,
                    role=role,
                    original_status=status,
                    reviewer_decision="Rejected",
                    reviewer_notes=notes or "",
                )
                st.warning(f"Rejected: {emp_id} / {role}")
                st.rerun()

            # ── Regenerate ───────────────────────────────────────────────────
            if b3.button("🔄 Regenerate", key=f"regen_{cid}"):
                with st.spinner(f"Regenerating plan for {emp_id} / {role}…"):
                    new_result = compare(emp_id, role)
                new_status = new_result.get("overall_status", "Unknown")
                st.info(
                    f"Regenerated plan. New status: **{new_status}**. "
                    "A new comparison record has been added — original is preserved."
                )
                st.rerun()

st.divider()

# ── 5. Full comparison history table ─────────────────────────────────────────
with st.expander("📜 Full Comparison History", expanded=False):
    try:
        if not comp_df.empty:
            display_df = comp_df[[
                "employee_id", "role", "overall_status",
                "coverage_score", "traceability_score", "timestamp"
            ]].copy()
            display_df.columns = [
                "Employee ID", "Role", "Status",
                "Coverage %", "Traceability %", "Timestamp"
            ]
            display_df["Coverage %"]     = display_df["Coverage %"].round(1)
            display_df["Traceability %"] = display_df["Traceability %"].round(1)
            st.dataframe(display_df, use_container_width=True, hide_index=True)
        else:
            st.info("No comparison history yet.")
    except Exception as exc:
        st.error(f"Error loading history: {exc}")
